language: node_js
node_js:
- '4'
cache:
  directories:
  - "$HOME/.npm"
deploy:
  provider: npm
  email: kellyselden@gmail.com
  api_key:
    secure: hXEzR0R8bTah+eR/z41bz/hhfJhR9sQbdq1Mfsz+P9rvOwx+duHF4zI61TSEFSi/G4C9kfoLELMWw6SJv7SesGkIl+TugS2KJbZYQ2yuaDwQNlNWHu/1+MBnputLqUQd4xZrw593PD3DzqjbNYSeAa19oHA1Pz86omxUaUspxfHnYM1tSQRZxC0AA90DGUKT3AHHrgZjYXeEdwd8EorlVA3OhzjkIsd7GtJuSIS1rf50xi0TU41QvBHni7ZV51a/oDtzJYkOudEaUt02Koh3hVh2jpdMruSvuXqxcAIp+KXJvbkl9/GMxBAEw4fPB+pd/+rtFkNSHojXfVRC0FBPgDYSFQb+aXGk+ugBirUAXGAav1VLjV5R9PZHENbeWfN1js3VRv3EDOxWTro/rj/btfga6XwqHzmTVQpx/YNemeENrZ9OLMaR2u4z69yttH6JkXAK9bCiPqi4CyMdqeLaYqWfhAuFUV/rQAcveL2p37MX3eiCpg0kQJiuLSAErKQA9jCjZS7u4DwjQNiSjhLzVHlwv/KT0FLk2civhCEMsri/7B23wt/pmm3bxxALaCJpzD0U4zaNCCpnvohoGmUz25Xrjfd86fm9i9rSVdqiENvI6kVuoQegzI3lp5hJZIC+l9rKVjWrH+14QLSfTKMKiHovVMWjZqBA0p+zFTtlmx4=
  on:
    tags: true
    repo: kellyselden/git-fixtures
